# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdownpage',
            name='slag',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
    ]
