# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_markdownpage_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markdownpage',
            old_name='slag',
            new_name='path',
        ),
    ]
