# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160306_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdownpage',
            name='path',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
